import bpy


class AIHelperProperties(bpy.types.PropertyGroup):
    prompt: bpy.props.StringProperty(
        name="Prompt",
        description="Describe the operation to run on the selection",
        default="",
    )
    tool_calls_json: bpy.props.StringProperty(
        name="Tool Calls",
        description="Preview of tool calls generated by the LLM",
        default="",
    )
    last_solver_report: bpy.props.StringProperty(
        name="Solver Report",
        description="Last solver summary",
        default="",
    )
    auto_rebuild: bpy.props.BoolProperty(
        name="Auto Rebuild 3D Ops",
        description="Automatically rebuild 3D ops when sketch updates",
        default=True,
    )


def register():
    bpy.utils.register_class(AIHelperProperties)
    bpy.types.Scene.ai_helper = bpy.props.PointerProperty(type=AIHelperProperties)


def unregister():
    del bpy.types.Scene.ai_helper
    bpy.utils.unregister_class(AIHelperProperties)
