import bpy

from .llm.presets import preset_items
from .llm.recipes import recipe_items


class AIHelperProperties(bpy.types.PropertyGroup):
    prompt: bpy.props.StringProperty(
        name="Prompt",
        description="Describe the operation to run on the selection",
        default="",
    )
    prompt_preset: bpy.props.EnumProperty(
        name="Preset",
        description="Preset prompt templates",
        items=preset_items(),
        default="NONE",
    )
    prompt_recipe: bpy.props.EnumProperty(
        name="Recipe",
        description="Prompt recipes for common LLM workflows",
        items=recipe_items(),
        default="NONE",
    )
    image_path: bpy.props.StringProperty(
        name="Image Path",
        description="Optional image for LLM sketch generation",
        default="",
        subtype="FILE_PATH",
    )
    image_url: bpy.props.StringProperty(
        name="Image URL",
        description="HTTPS image URL for vision models",
        default="",
    )
    image_notes: bpy.props.StringProperty(
        name="Image Notes",
        description="Notes to guide image-based sketch generation",
        default="",
    )
    tool_calls_json: bpy.props.StringProperty(
        name="Tool Calls",
        description="Preview of tool calls generated by the LLM",
        default="",
    )
    last_solver_report: bpy.props.StringProperty(
        name="Solver Report",
        description="Last solver summary",
        default="",
    )
    last_solver_details: bpy.props.StringProperty(
        name="Solver Details",
        description="Top constraint errors",
        default="",
    )
    last_solver_worst_id: bpy.props.StringProperty(
        name="Solver Worst ID",
        description="Constraint id with the largest error",
        default="",
    )
    auto_rebuild: bpy.props.BoolProperty(
        name="Auto Rebuild 3D Ops",
        description="Automatically rebuild 3D ops when sketch updates",
        default=True,
    )
    auto_constraints: bpy.props.BoolProperty(
        name="Auto Constraints",
        description="Auto-apply horizontal/vertical constraints when drawing",
        default=True,
    )
    hv_tolerance_deg: bpy.props.FloatProperty(
        name="HV Tolerance",
        description="Angle tolerance in degrees for auto H/V constraints",
        default=8.0,
        min=0.1,
        max=45.0,
    )
    snap_enabled: bpy.props.BoolProperty(
        name="Snap Enabled",
        description="Enable snapping while drawing",
        default=True,
    )
    snap_grid: bpy.props.BoolProperty(
        name="Snap Grid",
        description="Snap to grid points",
        default=True,
    )
    snap_verts: bpy.props.BoolProperty(
        name="Snap Vertices",
        description="Snap to vertices",
        default=True,
    )
    snap_mids: bpy.props.BoolProperty(
        name="Snap Midpoints",
        description="Snap to edge midpoints",
        default=True,
    )
    snap_inters: bpy.props.BoolProperty(
        name="Snap Intersections",
        description="Snap to edge intersections",
        default=True,
    )
    angle_snap_enabled: bpy.props.BoolProperty(
        name="Angle Snap",
        description="Snap angles to fixed increments while drawing",
        default=False,
    )
    angle_snap_deg: bpy.props.FloatProperty(
        name="Angle Snap Deg",
        description="Angle snap increment in degrees",
        default=15.0,
        min=1.0,
        max=90.0,
    )
    snap_radius: bpy.props.FloatProperty(
        name="Snap Radius",
        description="Snap radius in scene units",
        default=0.25,
        min=0.0,
    )
    grid_step: bpy.props.FloatProperty(
        name="Grid Step",
        description="Grid step in scene units",
        default=1.0,
        min=0.001,
    )
    inspector_selection_key: bpy.props.StringProperty(
        name="Inspector Selection Key",
        description="Selection signature for inspector updates",
        default="",
    )
    inspector_vertex_x: bpy.props.FloatProperty(
        name="Vertex X",
        description="Inspector vertex X",
        default=0.0,
    )
    inspector_vertex_y: bpy.props.FloatProperty(
        name="Vertex Y",
        description="Inspector vertex Y",
        default=0.0,
    )
    inspector_edge_length: bpy.props.FloatProperty(
        name="Edge Length",
        description="Inspector edge length",
        min=0.0,
        default=1.0,
    )
    inspector_edge_angle: bpy.props.FloatProperty(
        name="Edge Angle",
        description="Inspector edge angle (degrees)",
        default=0.0,
    )
    inspector_edge_anchor: bpy.props.EnumProperty(
        name="Edge Anchor",
        description="Anchor for edge edits",
        items=[
            ("START", "Start", "Keep the first vertex fixed"),
            ("END", "End", "Keep the second vertex fixed"),
            ("CENTER", "Center", "Keep the midpoint fixed"),
        ],
        default="START",
    )
    inspector_arc_center_x: bpy.props.FloatProperty(
        name="Arc Center X",
        description="Inspector arc center X",
        default=0.0,
    )
    inspector_arc_center_y: bpy.props.FloatProperty(
        name="Arc Center Y",
        description="Inspector arc center Y",
        default=0.0,
    )
    inspector_arc_radius: bpy.props.FloatProperty(
        name="Arc Radius",
        description="Inspector arc radius",
        min=0.0,
        default=1.0,
    )
    inspector_arc_start_angle: bpy.props.FloatProperty(
        name="Arc Start Angle",
        description="Inspector arc start angle (degrees)",
        default=0.0,
    )
    inspector_arc_end_angle: bpy.props.FloatProperty(
        name="Arc End Angle",
        description="Inspector arc end angle (degrees)",
        default=90.0,
    )
    inspector_arc_clockwise: bpy.props.BoolProperty(
        name="Arc Clockwise",
        description="Inspector arc clockwise flag",
        default=False,
    )
    inspector_rect_center_x: bpy.props.FloatProperty(
        name="Rect Center X",
        description="Inspector rectangle center X",
        default=0.0,
    )
    inspector_rect_center_y: bpy.props.FloatProperty(
        name="Rect Center Y",
        description="Inspector rectangle center Y",
        default=0.0,
    )
    inspector_rect_width: bpy.props.FloatProperty(
        name="Rect Width",
        description="Inspector rectangle width",
        min=0.0,
        default=1.0,
    )
    inspector_rect_height: bpy.props.FloatProperty(
        name="Rect Height",
        description="Inspector rectangle height",
        min=0.0,
        default=1.0,
    )
    inspector_rect_rotation: bpy.props.FloatProperty(
        name="Rect Rotation",
        description="Inspector rectangle rotation (degrees)",
        default=0.0,
    )


def register():
    bpy.utils.register_class(AIHelperProperties)
    bpy.types.Scene.ai_helper = bpy.props.PointerProperty(type=AIHelperProperties)


def unregister():
    del bpy.types.Scene.ai_helper
    bpy.utils.unregister_class(AIHelperProperties)
